project:
  type: website

  render:
    - index.qmd
    - about/
    - journeys/
    - ways-of-thinking/
    - writing/

resources:
  - data/

website:
  title: "Thinking Across Scales"

  navbar:
    left:
      - text: Home
        href: index.qmd

      - text: Atlas
        href: journeys/index.qmd

      - text: Essays
        href: ways-of-thinking/index.qmd

      - text: Writing
        href: writing/index.qmd

      - text: About
        href: about/index.qmd
format:
  html:
    css: assets/css/custom.css
    page-layout: full
    toc: false
    title-block-banner: false
